from backend import db

class PlayerWeeklyStats(db.Model):
    __tablename__ = 'PlayerWeeklyStats'
    player_id = db.Column(db.String(50), primary_key=True)
    season = db.Column(db.Integer, primary_key=True)
    season_type = db.Column(db.String(20), primary_key=True)
    week = db.Column(db.Integer, primary_key=True)
    team_id = db.Column(db.String(10), db.ForeignKey('DimTeams.team_id'))

    shotgun = db.Column(db.Integer)
    first_down_pass = db.Column(db.Integer)
    third_down_failed = db.Column(db.Integer)
    yptouch = db.Column(db.Float)
    team_offense_snaps = db.Column(db.Integer)
    fantasy_points_ppr = db.Column(db.Float)
    fumble_lost = db.Column(db.Integer)
    fumble_out_of_bounds = db.Column(db.Integer)
    rush_touchdown = db.Column(db.Integer)
    fourth_down_failed = db.Column(db.Integer)
    pass_touchdown = db.Column(db.Integer)
    comp_pct = db.Column(db.Float)
    targets = db.Column(db.Integer)
    fourth_down_converted = db.Column(db.Integer)
    rush_td_pct = db.Column(db.Float)
    rush_attempts = db.Column(db.Integer)
    qb_dropback = db.Column(db.Integer)
    ypa = db.Column(db.Float)
    offense_pct = db.Column(db.Float)
    yards_after_catch = db.Column(db.Float)
    int_pct = db.Column(db.Float)
    rushing_yards = db.Column(db.Float)
    qb_scramble = db.Column(db.Integer)
    ypr = db.Column(db.Float)
    touches = db.Column(db.Integer)
    first_down_rush = db.Column(db.Integer)
    receptions = db.Column(db.Integer)
    no_huddle = db.Column(db.Integer)
    total_yards = db.Column(db.Float)
    ayptarget = db.Column(db.Float)
    passing_air_yards = db.Column(db.Float)
    passer_rating = db.Column(db.Float)
    adot = db.Column(db.Float)
    rec_td_pct = db.Column(db.Float)
    third_down_converted = db.Column(db.Integer)
    pass_attempts = db.Column(db.Integer)
    fantasy_points_standard = db.Column(db.Float)
    offense_snaps = db.Column(db.Integer)
    passing_yards = db.Column(db.Float)
    tackled_for_loss = db.Column(db.Integer)
    fumble_not_forced = db.Column(db.Integer)
    pass_td_pct = db.Column(db.Float)
    yptarget = db.Column(db.Float)
    ypc = db.Column(db.Float)
    total_tds = db.Column(db.Integer)
    fumble = db.Column(db.Integer)
    incomplete_pass = db.Column(db.Integer)
    air_yards_share = db.Column(db.Float)
    receiving_air_yards = db.Column(db.Float)
    receiving_yards = db.Column(db.Float)
    target_share = db.Column(db.Float)
    td_pct = db.Column(db.Float)
    receiving_touchdown = db.Column(db.Integer)
    complete_pass = db.Column(db.Integer)
    qb_hit = db.Column(db.Integer)
    defensive_extra_point_attempt = db.Column(db.Integer)
    defense_pct = db.Column(db.Float)
    team_defense_snaps = db.Column(db.Integer)
    tackle_with_assist = db.Column(db.Integer)
    assist_tackle = db.Column(db.Integer)
    defensive_two_point_conv = db.Column(db.Integer)
    defensive_two_point_attempt = db.Column(db.Integer)
    defense_snaps = db.Column(db.Integer)
    def_touchdown = db.Column(db.Integer)
    defensive_extra_point_conv = db.Column(db.Integer)
    sack = db.Column(db.Float)
    solo_tackle = db.Column(db.Integer)
    safety = db.Column(db.Integer)
    interception = db.Column(db.Integer)
    fumble_forced = db.Column(db.Integer)
    fumble_not_forced = db.Column(db.Integer)
    fumble_out_of_bounds = db.Column(db.Integer)